### PR TITLE
CMake integration

### PR DESCRIPTION
**Pull request by querat**
Hello,

I'm dabbling with game dev & ECSs those days, and stumbled upon your project while looking for some Entt examples. I wrote a CMakeLists.txt so I could build and try it myself.

My end goal was to have the project easily built without caring about installing its dependencies manually, so I could learn some CMake tricks.

I noticed @skypjack (thanks for Entt if you are reading this, by the way) was talking about creating a CMake file himself, so I'll be glad to take a look at it if mine is not good enough to be merged.

This CmakeLists hasn't been tested under Windows, but for now, it works fine under a linux environment.
it uses ExternalProject to "git clone" Entt's repo, then downloads and builds SDL 2.0.8 sources in the chosen CMake's build directory.
SDL2_gfx does not have a CMakeLists.txt in its sources directory, so a cross-platform way to build this dependency will be needed.

This is my first ever PR, so I hope it could be of use to your project. Any tip and feedback would be appreciated :)

Apparently I can't make a PR on a new branch (CMakeIntegration), so I am making this PR on the master branch.

### CODE REVIEW

**Comment by skypjack** [comment]
Thank you very much!! I've been a bit busy during the last days and I had not the chance to write the cmake file for this project yet. I'm glad to know you're getting in charge of doing it. Really appreciated.  
I'll review it, no doubts. Meanwhile, even if sdl gfx hasn't a cmake file, you can still compile it using the external stuff if it uses the autotools. Do you already know how to do it?

---

Oh, and do not forget to star both the projects!! It will help us to spread them more and more!! :+1:

**Comment by reworks-org** [comment]
I don't know if its different in CMake but in VS I just dropped sdl2_gfx into the project and it compiled fine.

Thanks for the contribution.

**Comment by querat** [comment]
@skypjack I managed to compile SDL2_gfx using autotools and GNU Make, but it feels way too hackish ... I think adding the sources @reworks placed into the repository to the project should work fine since that's what he has been doing so far, so I'll do this later.

I made sure to :star: both projects :)

**Comment by querat** [comment]
CMake support should be fine under linux now, unless I forgot a dependency that was already installed on my system.
I don't think the project can be built under Windows though, since I needed to link the project against dl and pthread libs. 
Not sure about MacOS either, and I don't have any dev environment in either of these OS.

Edit: it seems like the pthread and dl dependencies are only needed by SDL2, potentially only on unix-related systems. I'm adding a condition to only link them on UNIX, Linux & Apple

**Comment by reworks-org** [comment]
@rapier992 Thanks for that. It doesn't really matter it can't build windows, because those solution files in the repo are generic and should be enough for now. I will write some scripts to handle windows building better soon.

**Comment by reworks-org** [comment]
Does CMake support wildcards? ( * symbol ). It would make it easier to add source code if its something like

foreach in directory: src/*.cpp  or something. I know make does something similar.

**Comment by querat** [comment]
I like having all files defined personally. I'll see if I can change this for you since it will definitely be easier to manage if you are using another build system aside :).

**Comment by reworks-org** [comment]
@skypjack @rapier992 I've finished the features for the game. When the cmake script is done, then I can write up the travis-ci yml after.

**Pull request merged**
